const AboutContentMD = `
# Fundación Alicia Alonso

Tomando en consideración la incesante demanda de las industrias culturales, nosotros damos espacio a creadores e interpretes para enfocar su pasión en el afán de mostar al mundo a través del arte la simple y emocionante razón de la condición humana. Mantenemos nuestro brillo promoviendo un arte ecléctico y de excelencia. Son 25 años siendo la vanguardia en formación universitaria en artes escénicas y de posgrado, llevando el ballet clásico por toda España, generando piezas de nueva creación en colaboración con artistas y profesionales consagrados y nuestras continuas ganas de hacer nos han convertido desde hace un año en la conexión de este país con el mundo internacional del teatro.

![](https://res.cloudinary.com/huh9ixig7/image/upload/v1553719514/default_images/aa_infographic.png)

## El Instituto Universitario

El Instituto Universitario Alicia Alonso es un centro de la Fundación Alicia Alonso adscrito a la Universidad Rey Juan Carlos y miembro del ejecutivo del Comité Internacional de la Danza UNESCO. Esta organización es pionera en España habiendo implantado las primeras titulaciones oficiales en Danza. En la actualidad imparte los Grados Universitarios en Artes Visuales y Danza, los Grados Superiores en Danza, el Master en Artes Escénicas, y el Master en Gestión y Liderazgo de Proyectos Culturales. Entre sus programas académicos también se encuentran varias líneas de investigación del Doctorado en Arte de la Universidad Rey Juan Carlos, los Títulos Propios Master en Estudios de la India y el Curso de Especialista en Danzas Tradicionales.

**2014: GRAND PRIX ALASSIO**
Por el desarrollo de las metodologías y técnicas para la enseñanza del ballet clásico.
**2013: PREMIO CIUDAD DE BARCELONA**
Por el desarrollo de la Investigación en Danza y por la proyección internacional de la labor del Instituto Universitario de la Danza Alicia Alonso.
**2005: PREMIO NACIONAL A LA MEJOR INSTITUCIÓN DOCENTE DE ENSEÑANZAS ARTÍSTICAS SUPERIORES.**
El Jurado de Cultura Viva, integrado por destacados académicos e investigadores del Consejo Superior de Investigaciones Científicas de España otorgó este galardón en su XV edición al Centro, por su excelencia académica, su impulso a la investigación, a la creación artística de calidad y su proyección internacional. Desde entonces continúa siendo un centro europeo de referencia.

## Ballet de Cámara de Madrid

Fundado en 1997 bajo la Dirección General de Alicia Alonso y con la participación de Alberto García Castaño, Director Ejecutivo, quien junto a destacados Maîtres del Ballet Nacional de Cuba ha sido gran impulsor de este proyecto. Su creación responde a la necesidad de asegurar el desempeño profesional a los alumnos del Instituto Universitario, y ofrecer un marco de creación para jóvenes coreógrafos. Su objetivo es que los bailarines completen su andadura en el camino hacia la madurez escénica. Para cumplimentar esta tarea, la Compañía realiza una media de veinte funciones anuales en teatros de la Red de la Comunidad de Madrid, además de giras nacionales e internacionales.
La agrupación posee un amplio repertorio que abarca la danza clásica, contemporánea, española y el teatro físico del movimiento. A lo largo de estos años ha realizado más de trescientas representaciones y participado en festivales y concursos nacionales e internacionales. En los últimos años ha podido contar entre sus filas a los bailarines galardonados con los Premios Nacionales de Danza Clásica convocados por el Ministerio de Educación, Cultura y Deporte. Suma a su currículo los premios obtenidos en eventos tales como: el Concurso Iberoamericano de Coreografía, el Concurso Internacional Burgos-New York, el Concurso Nacional de Castellón de la Plana, el Concurso Coreográfico de la Comunidad de Madrid o como finalistas del Concurso Coreográfico de la Fundación Onassis, entre otros muchos reconocimientos.

## Teatro de Cámara de Madrid

Desde el año 2010 como resultado de los procesos de investigación de creación escénica, la compañía Teatro de Cámara de Madrid promociona sus mejores proyectos teatrales estrenándolos en diferentes espacios escénicos internacionales y festivales de teatro joven. Sus integrantes han sido formados y dirigidos por actores y directores con relevante experiencia en la escena contemporánea  española y profesores del IUDAA. Desde el último año mientras cursan el Grado Oficial Universitario en Artes Visuales y Danza, con mención en Teatro Físico y hasta  dos años posterior a su graduación, los intérpretes más relevantes, asumen los roles protagónicos de las piezas que quedan en repertorio de la compañía. De este modo comienzan sus prácticas pre-profesionales, vinculándose orgánicamente con la Industria Cultural.
Con sus puestas en escena se han presentado en diferentes festivales como “Segovia en Danza”, “Festival de Artes Escénicas” (Junta Municipal del Retiro/Madrid)  o  el “Certamen de Teatro Joven de Salamanca”, donde han sido galardonados en dos ocasiones con el 1er Premio a “Mejor puesta en escena”. Además cada año hacen pequeñas temporadas de representaciones en el teatro del Círculo de Bellas Artes de Madrid, en el Teatro “Tomas y Valiente” de Fuenlabrada. Durante 6 años han participado en proyectos artísticos de inmersión social, llevando el teatro y la danza a Centros Penitenciarios y Centros de Educación Especial en diversidad y discapacidad funcional.

## El Repositorio de Danza

El Repositorio Digital de Danza es un proyecto impulsado por el Fondo Documental y de Investigación del Instituto Universitario de la Danza Alicia Alonso con el objetivo de organizar, archivar, preservar y difundir, como información digital, fondos documentales relacionados con el arte de la danza y permitir el acceso a los mismos.
La aspiración de este proyecto es reunir o referenciar toda la información posible sobre los creadores y las creaciones artísticas del arte de la danza de España en particular y del resto del mundo.
La obtención en el año 2011 de las ayudas del Ministerio de Cultura para la creación y transformación de recursos digitales y su difusión y preservación mediante repositorios permitió terminar la primera fase del proyecto con la inclusión del archivo documental de Alicia Alonso, figura esencial de la danza en el siglo XX, así como importantes fondos del Museo de la Danza de Cuba, el Fondo Documental del Instituto Universitario de Danza “Alicia Alonso” y su compañía artística ballet de Cámara de Madrid, así como la producción investigadora sobre artes escénicas desarrollada en el instituto y en la URJC en los formatos de libros, artículos, tesis doctorales, y trabajos finales de máster y de grado.
La colaboración de los servicios de biblioteca de la URJC y la inserción del repositorio en la estructura del repositorio de la universidad URJC Digital permitió que el Repositorio de Danza se haya concretado como un aporte necesario al aún incipiente campo de estudio de la investigación de la Danza y las Artes Escénicas en España. Ha permitido situar en acceso libre una documentación imprescindible para la formación de una masa crítica de estudios en este ámbito y brindar un apoyo importante a la docencia, específicamente de nivel universitario en enseñanzas artísticas.
Las fases realizadas del proyecto han dado como resultado la construcción de un espacio de referencia internacional para el conocimiento, la docencia y la investigación en danza y artes escénicas en general. A partir de su existencia, personalidades, creadores y estudiosos españoles y de otros países se han interesado en este trabajo y han accedido a colaborar con su desarrollo. Entre estos podemos citar el Archivo de Antonio Gades, Tamara Rojo, Ramiro Guerra, y gestores de otros fondos documentales relacionados que ya están siendo preparados para la digitalización, descripción y transformación, en una segunda etapa del proyecto.
El Repositorio Digital de Danza ha sido incluído en grandes bibliotecas virtuales Como Hispana y Europeana, entre otras.

## Centro ITI España

Durante el 34° Congreso Mundial organizado en 2015 en Erevan, capital de Armenia, el Instituto Universitario de Danza Alicia Alonso fue seleccionado como Centro ITI España, canto por su trayectoria como por la estrecha vinculación entre creación artística, formación académica e investigación que ha distinguido su labor durance 25 años.`

export default AboutContentMD